# Generated by Django 2.0.7 on 2018-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burritobot', '0004_auto_20180712_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='command',
            name='response',
            field=models.CharField(max_length=500),
        ),
    ]
