# Generated by Django 2.0.7 on 2018-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burritobot', '0002_auto_20180707_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchuser',
            name='email',
            field=models.EmailField(max_length=500),
        ),
    ]
